MVC/WebSupplier/src/webApp/WebSupplier.WebApp/Models/Product/EditProductViewModel.cs
using Microsoft.AspNetCore.Http;
using WebSupplier.WebApp.Extensions.DataAnnotation.Product;
using WebSupplier.WebApp.Models.Category;
using WebSupplier.WebApp.Models.Supplier;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;

namespace WebSupplier.WebApp.Models.Product
{
    public class EditProductViewModel
    {
        //Atributos do dominio necessarios para criação do produto.
        public Guid Id { get; set; }

        [Required(ErrorMessage = "The field is mandatory.")]
        [StringLength(256, MinimumLength = 2, ErrorMessage = "The field must contain between 2 and 100 characters.")]
        [Display(Name = "Name")]
        public string Name { get; set; }

        [Required(ErrorMessage = "The field is mandatory.")]
        [StringLength(14, MinimumLength = 12, ErrorMessage = "The field must contain between {2} e {1} characters.")]
        [Display(Name = "BarCode")]
        public string BarCode { get; set; }

        [Required(ErrorMessage = "The field is mandatory.")]
        [Range(0, int.MaxValue)]
        [Display(Name = "Stock")]
        public int QuantityStock { get; set; }

        [Display(Name = "Active")]
        public bool Active { get; set; }

        [Display(Name = "Sales Price")]
        [Required(ErrorMessage = "The field is mandatory.")]
        [Range(0.2, double.MaxValue)]
        [PriceSalesAttribute]
        public decimal PriceSales { get; set; }

        [Required(ErrorMessage = "The field is mandatory.")]
        [Range(0.1, double.MaxValue)]
        [Display(Name = "Purchase Price")]
        public decimal PricePurchase { get; set; }

        public Guid CategoryId { get; set; }
        public CategoryViewModel Category { get; set; }

        public Guid SupplierId { get; set; }
        public SupplierViewModel Supplier { get; set; }

        public ICollection<EditImageViewModel> Images { get; set; } = new List<EditImageViewModel>();


        //Daqui para baixo são elementos responsaveis pelo o funcionamento da tela.
        public IEnumerable<SupplierViewModel> ListSupplier { get; set; } = new List<SupplierViewModel>();
        public IEnumerable<CategoryViewModel> ListCategory { get; set; } = new List<CategoryViewModel>();

        public IFormFile ImageOne { get; set; }
        public IFormFile ImageTwo { get; set; }
        public IFormFile ImageTree { get; set; }
        public IFormFile ImageFor { get; set; }
        public IFormFile ImageFive { get; set; }

        public string GetImageOne()
        {
            return Images?.ToList().Count >= 1 ? "product/" + Images.ToList()?[0].ImagePath : "/image.svg";
        }
        public string GetImageTwo()
        {
            return Images?.ToList().Count >= 2 ? "product/" + Images.ToList()?[1].ImagePath : "/image.svg";
        }

        public string GetImageTree()
        {
            return Images?.ToList().Count >= 3 ? "product/" + Images.ToList()?[2].ImagePath : "/image.svg";
        }

        public string GetImageFor()
        {
            return Images?.ToList().Count >= 4 ? "product/" + Images.ToList()?[3].ImagePath : "/image.svg";
        }

        public string GetImageFive()
        {
            return Images?.ToList().Count >= 5 ? "product/" + Images.ToList()?[4].ImagePath : "/image.svg";
        }

    }

    public class EditImageViewModel
    {
        public Guid Id { get; set; }
        public string ImagePath { get; set; }
    }
}

MVC/WebSupplier/src/webApp/WebSupplier.WebApp/Models/Product/NewProductViewModel.cs
using Microsoft.AspNetCore.Http;
using WebSupplier.WebApp.Extensions.DataAnnotation.Product;
using WebSupplier.WebApp.Models.Category;
using WebSupplier.WebApp.Models.Supplier;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;

namespace WebSupplier.WebApp.Models.Product
{
    public class NewProductViewModel
    {
        //Atributos do dominio necessarios para criação do produto.

        [Required(ErrorMessage = "The field is mandatory.")]
        [StringLength(256, MinimumLength = 2, ErrorMessage = "The field must contains between 2 and 100 characters.")]
        [Display(Name = "Name")]
        public string Name { get; set; }

        [Required(ErrorMessage = "The field is mandatory.")]
        [StringLength(14, MinimumLength = 12, ErrorMessage = "The field must contains between {2} e {1} characters.")]
        [Display(Name = "BarCode")]
        public string BarCode { get; set; }

        [Required(ErrorMessage = "The field is mandatory.")]
        [Range(0, int.MaxValue)]
        [Display(Name = "Stock")]
        public int QuantityStock { get; set; }

        [Display(Name = "Active")]
        public bool Active { get; set; }

        [Display(Name = "Sales Price")]
        [Required(ErrorMessage = "The field is mandatory.")]
        [Range(0.2, double.MaxValue)]
        [PriceSalesAttribute]
        public decimal PriceSales { get; set; }

        [Required(ErrorMessage = "The field is mandatory.")]
        [Range(0.1, double.MaxValue)]
        [Display(Name = "Purchase Price")]
        public decimal PricePurchase { get; set; }

        public Guid CategoryId { get; set; }
        public CategoryViewModel Category { get; set; }

        public Guid SupplierId { get; set; }
        public SupplierViewModel Supplier { get; set; }

        public ICollection<NewImageViewModel> Images { get; set; } = new List<NewImageViewModel>();


        //Daqui para baixo são elementos responsaveis pelo o funcionamento da tela.
        public IEnumerable<SupplierViewModel> ListSupplier { get; set; } = new List<SupplierViewModel>();
        public IEnumerable<CategoryViewModel> ListCategory { get; set; } = new List<CategoryViewModel>();

        public IFormFile ImageOne { get; set; }
        public IFormFile ImageTwo { get; set; }
        public IFormFile ImageTree { get; set; }
        public IFormFile ImageFor { get; set; }
        public IFormFile ImageFive { get; set; }

        public string GetImageOne()
        {
            return Images?.ToList().Count >= 1 ? "temp/" + Images.ToList()?[0].ImagePath : "/image.svg";
        }
        public string GetImageTwo()
        {
            return Images?.ToList().Count >= 2 ? "temp/" + Images.ToList()?[1].ImagePath : "/image.svg";
        }

        public string GetImageTree()
        {
            return Images?.ToList().Count >= 3 ? "temp/" + Images.ToList()?[2].ImagePath : "/image.svg";
        }

        public string GetImageFor()
        {
            return Images?.ToList().Count >= 4 ? "temp/" + Images.ToList()?[3].ImagePath : "/image.svg";
        }

        public string GetImageFive()
        {
            return Images?.ToList().Count >= 5 ? "temp/" + Images.ToList()?[4].ImagePath : "/image.svg";
        }

    }

    public class NewImageViewModel
    {
        public string ImagePath { get; set; }
    }    

    
}

MVC/WebSupplier/src/webApp/WebSupplier.WebApp/Models/Product/ProductViewModel.cs
using Microsoft.AspNetCore.Http;
using WebSupplier.WebApp.Models.Category;
using WebSupplier.WebApp.Models.Supplier;
using System;
using System.Collections.Generic;
using System.Linq;

namespace WebSupplier.WebApp.Models.Product
{
    public class ProductViewModel
    {
        public Guid Id { get; set; }
        public Guid CategoryId { get; set; }
        public Guid SupplierId { get; set; }

        public string Name { get; set; }
        public string BarCode { get; set; }
        public int QuantityStock { get; set; }
        public bool Active { get; set; }
        public decimal PriceSales { get; set; }
        public decimal PricePurchase { get; set; }

        public CategoryViewModel Category { get; set; }
        public SupplierViewModel Supplier { get; set; }
        public IEnumerable<ImageViewModel> Images { get; set; }

        public DateTime InsertDate { get; set; }

        //Daqui para baixo são elementos responsaveis pelo o funcionamento da tela.        

        public string GetImageOne()
        {
            return Images?.ToList().Count >= 1 ? "product/" + Images.ToList()?[0].ImagePath : "/image.svg";
        }
        public string GetImageTwo()
        {
            return Images?.ToList().Count >= 2 ? "product/" + Images.ToList()?[1].ImagePath : "/image.svg";
        }

        public string GetImageTree()
        {
            return Images?.ToList().Count >= 3 ? "product/" + Images.ToList()?[2].ImagePath : "/image.svg";
        }

        public string GetImageFor()
        {
            return Images?.ToList().Count >= 4 ? "product/" + Images.ToList()?[3].ImagePath : "/image.svg";
        }

        public string GetImageFive()
        {
            return Images?.ToList().Count >= 5 ? "product/" + Images.ToList()?[4].ImagePath : "/image.svg";
        }
    }

    public class ImageViewModel
    {
        public string ImagePath { get; set; }
    }
}

MVC/WebSupplier/src/webApp/WebSupplier.WebApp/Controllers/ProductController.cs
using AutoMapper;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using WebSupplier.Domain.Interfaces;
using WebSupplier.Domain.Interfaces.Services;
using WebSupplier.Domain.Models;
using WebSupplier.WebApp.Extensions;
using WebSupplier.WebApp.Models;
using WebSupplier.WebApp.Models.Category;
using WebSupplier.WebApp.Models.Product;
using WebSupplier.WebApp.Models.Supplier;
using System;
using System.Collections.Generic;
using System.Threading.Tasks;

namespace WebSupplier.WebApp.Controllers
{
    [Route("products")]
    public class ProductController : MainController
    {
        private readonly IProductService _productService;
        private readonly ISupplierService _supplierService;
        private readonly ICategoryService _categoryService;
        private readonly IImageService _imageService;
        public ProductController(INotificationService notificationService,
                                    IMapper mapper,
                                    IProductService productService,
                                    ISupplierService supplierService,
                                    ICategoryService categoryService, 
                                    IImageService imageService)
                                    : base(notificationService, mapper)
        {
            _productService = productService;
            _supplierService = supplierService;
            _categoryService = categoryService;
            _imageService = imageService;
        }

        [AllowAnonymous]
        [HttpGet("all-products")]
        public async Task<IActionResult> Index(int pageSize = 10, int pageIndex = 1, string query = null)
        {
            var result = await _productService.Pagination(pageIndex, pageSize, query);

            result.Query = query;
            result.ReferenceAction = "Index";

            return View(_mapper.Map<PaginationViewModel<ProductViewModel>>(result));
        }

        [ClaimsAuthorizeAttribute("Product", "New")]
        [HttpGet("new-product")]
        public async Task<IActionResult> New()
        {

            return View(await PopulationSupplierAndCategory(new NewProductViewModel()));
        }

        [ClaimsAuthorizeAttribute("Product", "New")]
        [HttpPost("new-product")]
        public async Task<IActionResult> New(NewProductViewModel viewModel)
        {
            if (viewModel.Images.Count == 0)
                _imageService.StoreImageTemporary(viewModel.ImageOne, viewModel.ImageTwo, viewModel.ImageTree, viewModel.ImageFor, viewModel.ImageFive)
                    .ForEach(x => viewModel.Images.Add(new NewImageViewModel() { ImagePath = x }));

            if (!ModelState.IsValid) return View(await PopulationSupplierAndCategory(viewModel));

            await _productService.Insert(_mapper.Map<Product>(viewModel));

            if (OperationValid()) return View(await PopulationSupplierAndCategory(viewModel));

            return RedirectToAction(nameof(Index));
        }

        [AllowAnonymous]
        [HttpGet("new-product/{id:guid}")]
        public async Task<IActionResult> Details(Guid id)
        {
            if (id == Guid.Empty) return BadRequest();

            var result = await _productService.FindById(id);

            if (OperationValid())
            {
                TempData["Error"] = "Product not found.";
                return RedirectToAction(nameof(Index));
            }

            return View(_mapper.Map<ProductViewModel>(result));
        }

        [ClaimsAuthorizeAttribute("Product", "Edit")]
        [HttpGet("edit-product/{id:guid}")]
        public async Task<IActionResult> Edit(Guid id)
        {
            if (id == Guid.Empty) return BadRequest();

            var result = await _productService.FindById(id);

            if (OperationValid())
            {
                TempData["Error"] = "Product not found.";
                return RedirectToAction(nameof(Index));
            }

            return View(await PopulationSupplierAndCategory(_mapper.Map<EditProductViewModel>(result)));
        }

        [ClaimsAuthorizeAttribute("Product", "Edit")]
        [HttpPost("edit-product/{id:guid}")]
        public async Task<IActionResult> Edit(Guid id, EditProductViewModel viewModel)
        {
            if (id != viewModel.Id) return BadRequest();
            if (viewModel.Images.Count == 0)
                _imageService.StoreImageTemporary(viewModel.ImageOne, viewModel.ImageTwo, viewModel.ImageTree, viewModel.ImageFor, viewModel.ImageFive)
                    .ForEach(x => viewModel.Images.Add(new EditImageViewModel() { ImagePath = x }));

            if (!ModelState.IsValid) return View(await PopulationSupplierAndCategory(viewModel));

            await _productService.Update(_mapper.Map<Product>(viewModel));

            if (OperationValid()) return View(await PopulationSupplierAndCategory(viewModel));

            TempData["Success"] = "Product edited successfully.";
            return RedirectToAction(nameof(Edit), _mapper.Map<EditProductViewModel>(await _productService.FindById(id)));
        }

        [ClaimsAuthorizeAttribute("Product", "Delete")]
        [HttpGet("delete-product/{id:guid}")]
        public async Task<IActionResult> Delete(Guid id)
        {
            if (id == Guid.Empty) return BadRequest();

            var result = await _productService.FindById(id);

            if (OperationValid())
            {
                TempData["Error"] = "Product not found.";
                return RedirectToAction(nameof(Index));
            }

            return View(_mapper.Map<ProductViewModel>(result));
        }

        [ClaimsAuthorizeAttribute("Product", "Delete")]
        [HttpPost("delete-product")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> ConfirmDelete(Guid id)
        {
            if (id == Guid.Empty) return BadRequest();

            await _productService.Delete(id);

            if (OperationValid())
            {                
                return View(nameof(Delete), _mapper.Map<ProductViewModel>(await _productService.FindById(id)));
            }

            TempData["Success"] = "Registration excluded with success.";
            return RedirectToAction(nameof(Index));
        }

        private async Task<NewProductViewModel> PopulationSupplierAndCategory(NewProductViewModel viewModel)
        {
            viewModel.ListSupplier = _mapper.Map<IEnumerable<SupplierViewModel>>(await _supplierService.ToList());
            viewModel.ListCategory = _mapper.Map<IEnumerable<CategoryViewModel>>(await _categoryService.ToList());

            return viewModel;
        }

        private async Task<EditProductViewModel> PopulationSupplierAndCategory(EditProductViewModel viewModel)
        {
            viewModel.ListSupplier = _mapper.Map<IEnumerable<SupplierViewModel>>(await _supplierService.ToList());
            viewModel.ListCategory = _mapper.Map<IEnumerable<CategoryViewModel>>(await _categoryService.ToList());

            return viewModel;
        }
    }
}

MVC/WebSupplier/src/webApp/WebSupplier.WebApp/Extensions/ViewComponents/SummaryViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using WebSupplier.Domain.Interfaces;
using System.Linq;
using WebSupplier.WebApp.Models;

namespace WebSupplier.WebApp.Extensions.ViewComponents
{
    public class SummaryViewComponent : ViewComponent
    {
        private readonly INotificationService _notificationService;

        public SummaryViewComponent(INotificationService notificationService)
        {
            _notificationService = notificationService;
        }

        public IViewComponentResult Invoke()
        {
            var list = _notificationService.AllError().Select(x => x.Erro).ToList();
            list.ForEach(x => ViewData.ModelState.AddModelError(string.Empty, x + " <br />"));
            return View(list);
        }
    }

    public class PaginationViewComponent : ViewComponent
    {
        public IViewComponentResult Invoke(IPageViewModel modelPagination)
        {
            return View(modelPagination);
        }

    }
}

MVC/WebSupplier/src/webApp/WebSupplier.WebApp/Views/Product/Details.cshtml
@model ProductViewModel
@{
    ViewData["Title"] = "New Product";
}

<h1>@ViewData["Title"]</h1>
<br />
<br />
<vc:summary></vc:summary>



<div class="form-row">
    <div class="form-group col-md-10">
        <label asp-for="Supplier"></label>
        <input asp-for="Supplier.FantasyName" type="text" class="form-control">
        <span asp-validation-for="SupplierId" class="alert-danger"></span>
    </div>
</div>

<div class="form-row">
    <div class="form-group col-md-10">
        <label asp-for="Category"></label>
        <input asp-for="Category.Name" type="text" class="form-control">
        <span asp-validation-for="CategoryId" class="alert-danger"></span>
    </div>
</div>

<div class="form-row">
    <div class="form-group col-md-5">
        <label asp-for="Name"></label>
        <input asp-for="Name" type="text" class="form-control">
        <span asp-validation-for="Name" class="alert-danger"></span>
    </div>
    <div class="form-group col-md-5">
        <label asp-for="BarCode"></label>
        <input asp-for="BarCode" type="text" class="form-control">
        <span asp-validation-for="BarCode" class="alert-danger"></span>
    </div>
</div>

<div class="form-row">
    <div class="form-group col-md-3">
        <label asp-for="PricePurchase"></label>
        <input asp-for="PricePurchase" type="text" class="form-control">
        <span asp-validation-for="PricePurchase" class="alert-danger"></span>
    </div>
    <div class="form-group col-md-3">
        <label asp-for="PriceSales"></label>
        <input asp-for="PriceSales" type="text" class="form-control">
        <span asp-validation-for="PriceSales" class="alert-danger"></span>
    </div>
</div>

<div class="form-row">
    <div class="form-group col-md-3">
        <label asp-for="QuantityStock"></label>
        <input asp-for="QuantityStock" type="text" class="form-control">
        <span asp-validation-for="QuantityStock" class="alert-danger"></span>
    </div>
</div>
<div class="form-row">
    <div class="form-group col-md-6">
        <div class="form-check form-switch">
            <input class="form-check-input" type="checkbox" asp-for="Active" checked>
            <label class="form-check-label" asp-for="Active">Ativo</label>
        </div>
    </div>
</div>
<div class="row imagens">

    <div class="col-md-2">

        <img src="~/images/@Model.GetImageOne()" class="img-thumbnail " id="previewImageOne" />
    </div>

    <div class="col-md-2">

        <img src="~/images/@Model.GetImageTwo()" class="img-thumbnail " id="previewImageTwo" />
    </div>

    <div class="col-md-2">

        <img src="~/images/@Model.GetImageTree()" class="img-thumbnail " id="previewImageTree" />
    </div>

    <div class="col-md-2">

        <img src="~/images/@Model.GetImageFor()" class="img-thumbnail " id="previewImageFor" />
    </div>

    <div class="col-md-2">

        <img src="~/images/@Model.GetImageFive()" class="img-thumbnail " id="previewImageFive" />
    </div>
</div>

<br />


<a asp-action="Index" class="btn btn-primary">Back to the List</a>



@section Scripts {

            @{
            await Html.RenderPartialAsync("_ValidationScriptsPartial");
        }

}

MVC/WebSupplier/src/webApp/WebSupplier.WebApp/Views/Product/Edit.cshtml
@model EditProductViewModel
@{
    ViewData["Title"] = "New Product";
}

<h1>@ViewData["Title"]</h1>
<br />
<br />
<vc:summary></vc:summary>

<form asp-action="Edit" method="post" enctype="multipart/form-data">

    <input asp-for="Id" type="hidden">

    <div class="form-row">
        <div class="form-group col-md-10">
            <label asp-for="Supplier"></label>
            <select asp-for="SupplierId" asp-items="@(new SelectList(Model.ListSupplier,"Id","FantasyName"))" class="form-control">
                <option></option>
            </select>
            <span asp-validation-for="SupplierId" class="alert-danger"></span>
        </div>
    </div>

    <div class="form-row">
        <div class="form-group col-md-10">
            <label asp-for="Category"></label>
            <select asp-for="CategoryId" asp-items="@(new SelectList(Model.ListCategory,"Id","Name"))" class="form-control">
                <option></option>
            </select>
            <span asp-validation-for="CategoryId" class="alert-danger"></span>
        </div>
    </div>

    <div class="form-row">
        <div class="form-group col-md-5">
            <label asp-for="Name"></label>
            <input asp-for="Name" type="text" class="form-control">
            <span asp-validation-for="Name" class="alert-danger"></span>
        </div>
        <div class="form-group col-md-5">
            <label asp-for="BarCode"></label>
            <input asp-for="BarCode" type="text" class="form-control">
            <span asp-validation-for="BarCode" class="alert-danger"></span>
        </div>
    </div>

    <div class="form-row">
        <div class="form-group col-md-3">
            <label asp-for="PricePurchase"></label>
            <input asp-for="PricePurchase" type="text" class="form-control">
            <span asp-validation-for="PricePurchase" class="alert-danger"></span>
        </div>
        <div class="form-group col-md-3">
            <label asp-for="PriceSales"></label>
            <input asp-for="PriceSales" type="text" class="form-control">
            <span asp-validation-for="PriceSales" class="alert-danger"></span>
        </div>
    </div>

    <div class="form-row">
        <div class="form-group col-md-3">
            <label asp-for="QuantityStock"></label>
            <input asp-for="QuantityStock" type="text" class="form-control">
            <span asp-validation-for="QuantityStock" class="alert-danger"></span>
        </div>
    </div>
    <div class="form-row">
        <div class="form-group col-md-6">
            <div class="form-check form-switch">
                <input class="form-check-input" type="checkbox" asp-for="Active" checked>
                <label class="form-check-label" asp-for="Active">Ativo</label>
            </div>
        </div>
    </div>
    <div class="row imagens">

        <div class="col-md-2">
            <input asp-for="ImageOne" type="file" class="input-file" />
            <img src="~/images/@Model.GetImageOne()" class="img-thumbnail img-upload" id="previewImageOne" />
            <div class=" btn btn-danger btn-image-excluir">Excluir</div>
            <span asp-validation-for="ImageOne" class="text-danger"></span>
        </div>

        <div class="col-md-2">
            <input asp-for="ImageTwo" type="file" class="input-file" />
            <img src="~/images/@Model.GetImageTwo()" class="img-thumbnail img-upload" id="previewImageTwo" />
            <div class=" btn btn-danger btn-image-excluir">Excluir</div>
            <span asp-validation-for="ImageTwo" class="text-danger"></span>
        </div>

        <div class="col-md-2">
            <input asp-for="ImageTree" type="file" class="input-file" />
            <img src="~/images/@Model.GetImageTree()" class="img-thumbnail img-upload" id="previewImageTree" />
            <div class=" btn btn-danger btn-image-excluir">Excluir</div>
            <span asp-validation-for="ImageTree" class="text-danger"></span>
        </div>

        <div class="col-md-2">
            <input asp-for="ImageFor" type="file" class="input-file" />
            <img src="~/images/@Model.GetImageFor()" class="img-thumbnail img-upload" id="previewImageFor" />
            <div class=" btn btn-danger btn-image-excluir">Excluir</div>
            <span asp-validation-for="ImageFor" class="text-danger"></span>
        </div>

        <div class="col-md-2">
            <input asp-for="ImageFive" type="file" class="input-file" />
            <img src="~/images/@Model.GetImageFive()" class="img-thumbnail img-upload" id="previewImageFive" />
            <div class=" btn btn-danger btn-image-excluir">Excluir</div>
            <span asp-validation-for="ImageFive" class="text-danger"></span>
        </div>
    </div>

    <br />

    <button type="submit" class="btn btn-success">Register</button>
    <a asp-action="Index" class="btn btn-primary">Back to the list</a>
</form>


@section Scripts {

            @{
            await Html.RenderPartialAsync("_ValidationScriptsPartial");
        }

}

MVC/WebSupplier/src/webApp/WebSupplier.WebApp/Views/Product/Index.cshtml
@model PaginationViewModel<ProductViewModel>

@{ ViewData["Title"] = "Products"; }

<h1>@ViewData["Title"]</h1>
<br />
<br />

<vc:summary></vc:summary>

<form asp-action="Index" asp-controller="ProductController" method="get">
    <div class="form-row">
        <div class="form-group col-md-2">
            <select name="pageSize" id="pageSize" value="@TempData["Size"]" class="form-control">
                <option value="10">10</option>
                <option value="50">50</option>
                <option value="@int.MaxValue">All</option>
            </select>
        </div>
        <div class="form-group col-md-4"></div>

        <div class="form-group col-md-5">
            <input type="text" class="form-control" name="query" id="query" value="@TempData["Query"]" placeholder="Search for Products" />
        </div>
        <div class="form-group col-md-1">
            <button type="submit" class="btn-primary">Search</button>
            <br />
            <br />
        </div>

        @if (User.Identity.Name.Contains("@admin.com"))
        {
            <div class="form-group col-md-1">
                <a asp-action="New" class="btn btn-primary">Add Product</a>
            </div>
        }
    </div>
</form>

<table class="table">
    <thead class="thead-dark">
        <tr>
            <th scope="col">Name</th>
            <th scope="col">Register</th>
            <th scope="col">Actions</th>
        </tr>
    </thead>
    <tbody>

        @foreach (var item in Model.List)
        {
            <tr>
            <th>@item.Name</th>
            <td>@item.InsertDate</td>
            <td>
                <a asp-action="Edit" asp-route-id="@item.Id" class="btn btn-secondary">Edit</a>
                <a asp-action="Details" asp-route-id="@item.Id" class="btn btn-warning">Details</a>
                <a asp-action="Delete" asp-route-id="@item.Id" class="btn btn-danger">Delete</a>
            </td>
            </tr>}
    </tbody>
</table>

<vc:pagination model-pagination="@Model"></vc:pagination>

MVC/WebSupplier/src/webApp/WebSupplier.WebApp/Views/Product/New.cshtml
@model NewProductViewModel
@{
    ViewData["Title"] = "New Product";
}

<h1>@ViewData["Title"]</h1>
<br />
<br />

<vc:summary></vc:summary>

<form asp-action="New" method="post" enctype="multipart/form-data">

    <div class="form-row">
        <div class="form-group col-md-10">
            <label asp-for="Supplier"></label>
            <select asp-for="SupplierId" asp-items="@(new SelectList(Model.ListSupplier,"Id","FantasyName"))" class="form-control">
                <option></option>
            </select>
            <span asp-validation-for="SupplierId" class="alert-danger"></span>
        </div>
    </div>

    <div class="form-row">
        <div class="form-group col-md-10">
            <label asp-for="Category"></label>
            <select asp-for="CategoryId" asp-items="@(new SelectList(Model.ListCategory,"Id","Name"))" class="form-control">
                <option></option>
            </select>
            <span asp-validation-for="CategoryId" class="alert-danger"></span>
        </div>
    </div>

    <div class="form-row">
        <div class="form-group col-md-5">
            <label asp-for="Name"></label>
            <input asp-for="Name" type="text" class="form-control">
            <span asp-validation-for="Name" class="alert-danger"></span>
        </div>
        <div class="form-group col-md-5">
            <label asp-for="BarCode"></label>
            <input asp-for="BarCode" type="text" class="form-control">
            <span asp-validation-for="BarCode" class="alert-danger"></span>
        </div>
    </div>

    <div class="form-row">
        <div class="form-group col-md-3">
            <label asp-for="PricePurchase"></label>
            <input asp-for="PricePurchase" type="text" class="form-control">
            <span asp-validation-for="PricePurchase" class="alert-danger"></span>
        </div>
        <div class="form-group col-md-3">
            <label asp-for="PriceSales"></label>
            <input asp-for="PriceSales" type="text" class="form-control">
            <span asp-validation-for="PriceSales" class="alert-danger"></span>
        </div>
    </div>

    <div class="form-row">
        <div class="form-group col-md-3">
            <label asp-for="QuantityStock"></label>
            <input asp-for="QuantityStock" type="text" class="form-control">
            <span asp-validation-for="QuantityStock" class="alert-danger"></span>
        </div>
    </div>
    <div class="form-row">
        <div class="form-group col-md-6">
            <div class="form-check form-switch">
                <input class="form-check-input" type="checkbox" asp-for="Active" checked>
                <label class="form-check-label" asp-for="Active">Ativo</label>
            </div>
        </div>
    </div>

    <br />

    <button type="submit" class="btn btn-success">Register</button>
    <a asp-action="Index" class="btn btn-primary">Back to the List</a>
</form>


@section Scripts {

            @{
            await Html.RenderPartialAsync("_ValidationScriptsPartial");
        }

}